### ISSUE TITLE
JavaScript error / SiteTree disappearing

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-admin#958]
PR: https://github.com/silverstripe/silverstripe-admin/pull/959

This happens when viewing a “lumberjacked” page - not sure if that module is the only trigger for this bug...

https://github.com/silverstripe/silverstripe-admin/blob/a3eaf95bb2e37641d5a2f476807cc9696d55fac4/client/src/legacy/LeftAndMain.Tree.js#L301

> `Uncaught TypeError: r is not a function`

The error seems to be caused by sometimes not passing a third argument when calling this function... looks like a regression from https://github.com/silverstripe/silverstripe-admin/commit/1c548cb599563997687cd1062ff2a0985c43197e

I guess it just needs to be wrapped in an `if` statement

--- 

Edit:

Actually the error doesn’t seem to cause the tree break, it’s just collapsed at the very top level (the site name)

**Comment by taoceanz** [comment]
I've found this error too. It happens specifically when clicking into a third or lower level page that hasn't been opened yet. If a third or lower level page is clicked into, the error occurs, then hard reload the page and click on that page or an open sub page again and the error does occur.

**Comment by ScopeyNZ** [comment]
With these errors you might like int install a dev version of `admin` and `yarn dev` from inside the `silverstripe/admin` directory to get more informative error messages.
